package dev.rusty.app

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class UpdateRepositoryTest {

    // ---- parseRelease -------------------------------------------------------

    @Test
    fun parsesTagNotesAndUrl() {
        val json = """
            {"tag_name":"v1.2.0","html_url":"https://github.com/SerafiniJose/rusty/releases/tag/v1.2.0",
             "body":"- Start/stop control\n- Bug fixes"}
        """.trimIndent()
        val info = UpdateRepository.parseRelease(json)!!
        assertEquals("1.2.0", info.versionName)
        assertEquals("https://github.com/SerafiniJose/rusty/releases/tag/v1.2.0", info.releaseUrl)
        assertTrue(info.notes.contains("Start/stop control"))
    }

    @Test
    fun missingTagIsNull() {
        assertNull(UpdateRepository.parseRelease("""{"body":"notes","html_url":"x"}"""))
    }

    @Test
    fun malformedJsonIsNull() {
        assertNull(UpdateRepository.parseRelease("not json"))
    }

    @Test
    fun missingBodyOrUrlStillParsesWithFallbacks() {
        val info = UpdateRepository.parseRelease("""{"tag_name":"2.0.0"}""")!!
        assertEquals("2.0.0", info.versionName)
        assertTrue(info.notes.isEmpty())
        // No html_url → falls back to the releases page.
        assertTrue(info.releaseUrl.contains("/releases"))
    }

    @Test
    fun stripsAutoGeneratedFullChangelogFooter() {
        val json = """
            {"tag_name":"v1.2.0","body":"## What's Changed\n* Add thing\n\n**Full Changelog**: https://github.com/SerafiniJose/rusty/compare/v1.1.0...v1.2.0"}
        """.trimIndent()
        val info = UpdateRepository.parseRelease(json)!!
        assertTrue(info.notes.contains("Add thing"))
        assertFalse(info.notes.contains("Full Changelog"))
        assertFalse(info.notes.contains("compare"))
    }

    @Test
    fun tidiesMarkdownHeadersAndBullets() {
        val raw = "### Added\n- Start/stop control\n### Fixed\n* Route-following"
        val expected = "Added\n• Start/stop control\nFixed\n• Route-following"
        assertEquals(expected, UpdateRepository.cleanNotes(raw))
    }

    @Test
    fun preservesBulletIndentation() {
        assertEquals("• Top\n  • Nested", UpdateRepository.cleanNotes("- Top\n  - Nested"))
    }

    @Test
    fun plainProseIsUntouched() {
        val prose = "Fixes a crash on rotate and speeds up startup."
        assertEquals(prose, UpdateRepository.cleanNotes(prose))
    }

    // ---- isNewer ------------------------------------------------------------

    @Test
    fun detectsNewerVersions() {
        assertTrue(UpdateRepository.isNewer(current = "1.1.0", latest = "1.2.0"))
        assertTrue(UpdateRepository.isNewer(current = "1.1.0", latest = "2.0.0"))
        assertTrue(UpdateRepository.isNewer(current = "1.1.0", latest = "1.1.1"))
    }

    @Test
    fun equalOrOlderIsNotNewer() {
        assertFalse(UpdateRepository.isNewer(current = "1.1.0", latest = "1.1.0"))
        assertFalse(UpdateRepository.isNewer(current = "1.2.0", latest = "1.1.0"))
        assertFalse(UpdateRepository.isNewer(current = "2.0.0", latest = "1.9.9"))
    }

    @Test
    fun toleratesLeadingVAndWhitespace() {
        assertTrue(UpdateRepository.isNewer(current = "v1.1.0", latest = "v1.2.0"))
        assertFalse(UpdateRepository.isNewer(current = " 1.2.0 ", latest = "v1.2.0"))
    }

    @Test
    fun toleratesDifferingSegmentCounts() {
        assertFalse(UpdateRepository.isNewer(current = "1.2", latest = "1.2.0"))
        assertTrue(UpdateRepository.isNewer(current = "1.2", latest = "1.2.1"))
        assertTrue(UpdateRepository.isNewer(current = "1", latest = "1.0.1"))
    }

    @Test
    fun garbageVersionsNeverFalselyPrompt() {
        assertFalse(UpdateRepository.isNewer(current = "1.1.0", latest = "banana"))
        assertFalse(UpdateRepository.isNewer(current = "", latest = ""))
    }
}
