package dev.rusty.app

import java.net.URLDecoder
import org.json.JSONArray
import org.json.JSONObject

/**
 * A configured RTSP camera. [rtspUrl] never carries inline credentials after save — a URL typed
 * with a `user:pass@host` userinfo is split at save time via [CameraCodec.splitInlineCredentials]
 * and the credentials moved into [SecretStore] under [CameraStore.credentialKeys]. [id] is
 * generated by whoever creates the record ("cam_" + 8 hex chars); this type only defines the shape.
 */
data class CameraRecord(
    val id: String,
    val name: String,
    val rtspUrl: String,
    val snapshotUrl: String?,
    val audioEnabled: Boolean,
    val forceTcp: Boolean,
    val position: Int,
)

/** A URL with any inline userinfo credentials pulled out. [username]/[password] are null when the
 *  URL carried no userinfo; [password] is null (not empty) when the userinfo had no colon. */
data class SplitUrl(val url: String, val username: String?, val password: String?)

/**
 * JSON codec for [CameraRecord] lists (the `camera_list` pref value) and the inline-credential
 * splitter shared by any pasted URL (`rtsp://`, `http://` snapshot URLs, ...).
 */
object CameraCodec {
    fun encode(cameras: List<CameraRecord>): String {
        val arr = JSONArray()
        for (cam in cameras) {
            val obj = JSONObject()
            obj.put("id", cam.id)
            obj.put("name", cam.name)
            obj.put("rtspUrl", cam.rtspUrl)
            obj.put("snapshotUrl", cam.snapshotUrl ?: JSONObject.NULL)
            obj.put("audioEnabled", cam.audioEnabled)
            obj.put("forceTcp", cam.forceTcp)
            obj.put("position", cam.position)
            arr.put(obj)
        }
        return arr.toString()
    }

    /** Tolerant: malformed JSON decodes to an empty list rather than throwing; a missing optional
     *  field falls back to [CameraRecord]'s default (snapshotUrl=null, audioEnabled=false,
     *  forceTcp=true) so older-format stored records keep loading after a field is added. */
    fun decode(json: String?): List<CameraRecord> {
        if (json == null) return emptyList()
        val arr = try {
            JSONArray(json)
        } catch (e: Exception) {
            return emptyList()
        }
        val result = ArrayList<CameraRecord>(arr.length())
        for (i in 0 until arr.length()) {
            val obj = arr.optJSONObject(i) ?: continue
            val id = obj.optString("id", "")
            val name = obj.optString("name", "")
            val rtspUrl = obj.optString("rtspUrl", "")
            val snapshotUrl = if (obj.has("snapshotUrl") && !obj.isNull("snapshotUrl")) obj.optString("snapshotUrl") else null
            val audioEnabled = obj.optBoolean("audioEnabled", false)
            val forceTcp = obj.optBoolean("forceTcp", true)
            val position = obj.optInt("position", 0)
            result.add(CameraRecord(id, name, rtspUrl, snapshotUrl, audioEnabled, forceTcp, position))
        }
        return result
    }

    /**
     * Splits `scheme://[user[:pass]@]rest` into the credential-free URL plus the decoded username
     * and password. Applies to any scheme, not just `rtsp://` (Task 12 reuses it for snapshot
     * URLs). A URL with no userinfo (no `@` before the next `/`) passes through unchanged with both
     * credential fields null.
     */
    fun splitInlineCredentials(url: String): SplitUrl {
        val schemeSep = url.indexOf("://")
        if (schemeSep < 0) return SplitUrl(url, null, null)
        val scheme = url.substring(0, schemeSep + 3)
        val rest = url.substring(schemeSep + 3)

        val pathStart = rest.indexOfFirst { it == '/' || it == '?' || it == '#' }
        val authority = if (pathStart >= 0) rest.substring(0, pathStart) else rest
        val tail = if (pathStart >= 0) rest.substring(pathStart) else ""

        val atIdx = authority.lastIndexOf('@')
        if (atIdx < 0) return SplitUrl(url, null, null)

        val userinfo = authority.substring(0, atIdx)
        val host = authority.substring(atIdx + 1)
        if (userinfo.isEmpty()) return SplitUrl(scheme + host + tail, null, null)

        val colonIdx = userinfo.indexOf(':')
        val username: String
        val password: String?
        if (colonIdx < 0) {
            username = URLDecoder.decode(userinfo, "UTF-8")
            password = null
        } else {
            username = URLDecoder.decode(userinfo.substring(0, colonIdx), "UTF-8")
            password = URLDecoder.decode(userinfo.substring(colonIdx + 1), "UTF-8")
        }
        return SplitUrl(scheme + host + tail, username, password)
    }
}
